name: Test Site 10101
favicon: null
layout_spectrum: 0.4056
typography_spectrum: 0.22417
title: Just another lonely site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8c0bf9'
    - '#120000'
    - '#3694d8'
    - '#f3fefe'
    - '#654dd5'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
