name: Test Site 10101
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16816
title: Just another lonely site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000201'
    - '#014a12'
    - '#90e1a4'
    - '#13a22e'
    - '#37eb68'
  brandStrength: 0.25
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
