name: Test Site 10101
favicon: null
layout_spectrum: 0.8916
typography_spectrum: 0.16816
title: Just another lonely site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#00ff18'
    - '#ff0000'
    - '#8f7900'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
