name: Test Site 10101
favicon: null
layout_spectrum: 0.8916
typography_spectrum: 0.22417
title: Just another lonely site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#120000'
    - '#3694d8'
    - '#f3fefe'
    - '#2b5777'
    - '#8ac3e9'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
