name: Test Site 10101
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4409740187693387
title: Just another lonely site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9683122790884227
  lightness: 0.125
  saturation: 0.22305607330054045
  rhythmicContrast: 0.5
purpose: []
