typography_spectrum: 0.22417
color:
  brandColors:
    - '#8c0bf9'
    - '#120000'
    - '#3694d8'
    - '#f3fefe'
    - '#654dd5'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25361
analytics:
  google: null
  facebook: null
  twitter: null
name: Test Site 10101
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Spin and Go!
purpose: []
